[theme]
primaryColor = "#1DB954"
backgroundColor = "#121212"
secondaryBackgroundColor = "#181818"
textColor = "#FFFFFF"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true